RealESSI_SRC = $(realpath $(dir $(lastword $(MAKEFILE_LIST))))
RealESSI_Dependencies = $(realpath $(dir $(lastword $(MAKEFILE_LIST))))/../RealESSI_Dependencies


# ###################################################


ESSI_INCLUDES  = -I$(RealESSI_SRC)/ModifiedOpenSeesServices/matrix \
            -I$(RealESSI_SRC)/ModifiedOpenSeesServices/tagged \
            -I$(RealESSI_SRC)/ModifiedOpenSeesServices/material \
            -I$(RealESSI_SRC)/ModifiedOpenSeesServices/material/uniaxial \
            -I$(RealESSI_SRC)/ModifiedOpenSeesServices/material/uniaxial/fedeas \
            -I$(RealESSI_SRC)/ModifiedOpenSeesServices/material/backbone \
            -I$(RealESSI_SRC)/ModifiedOpenSeesServices/material/state \
            -I$(RealESSI_SRC)/ModifiedOpenSeesServices/material/state/stiffness \
            -I$(RealESSI_SRC)/ModifiedOpenSeesServices/material/state/unloading \
            -I$(RealESSI_SRC)/ModifiedOpenSeesServices/material/state/strength \
            -I$(RealESSI_SRC)/ModifiedOpenSeesServices/material/nD \
            -I$(RealESSI_SRC)/ModifiedOpenSeesServices/material/nD/soil \
            -I$(RealESSI_SRC)/ModifiedOpenSeesServices/material/nD/feap \
            -I$(RealESSI_SRC)/ModifiedOpenSeesServices/material/nD/FiniteDeformation \
            -I$(RealESSI_SRC)/ModifiedOpenSeesServices/material/nD/FiniteDeformation/fdFlow \
            -I$(RealESSI_SRC)/ModifiedOpenSeesServices/material/nD/FiniteDeformation/fdYield \
            -I$(RealESSI_SRC)/ModifiedOpenSeesServices/material/nD/FiniteDeformation/fdEvolution \
            -I$(RealESSI_SRC)/ModifiedOpenSeesServices/material/section \
            -I$(RealESSI_SRC)/ModifiedOpenSeesServices/material/section/repres/cell \
            -I$(RealESSI_SRC)/ModifiedOpenSeesServices/material/section/repres/patch \
            -I$(RealESSI_SRC)/ModifiedOpenSeesServices/material/section/repres/reinfBar \
            -I$(RealESSI_SRC)/ModifiedOpenSeesServices/material/section/repres/reinfLayer \
            -I$(RealESSI_SRC)/ModifiedOpenSeesServices/material/section/repres/section \
            -I$(RealESSI_SRC)/ModifiedOpenSeesServices/material/section/fiber \
            -I$(RealESSI_SRC)/ModifiedOpenSeesServices/material/section/yieldSurface \
            -I$(RealESSI_SRC)/ModifiedOpenSeesServices/material/yieldSurface/evolution \
            -I$(RealESSI_SRC)/ModifiedOpenSeesServices/material/yieldSurface/plasticHardeningMaterial \
            -I$(RealESSI_SRC)/ModifiedOpenSeesServices/material/yieldSurface/yieldSurfaceBC \
            -I$(RealESSI_SRC)/ModifiedOpenSeesServices/recorder \
            -I$(RealESSI_SRC)/ModifiedOpenSeesServices/handler \
            -I$(RealESSI_SRC)/ModifiedOpenSeesServices/database \
            -I$(RealESSI_SRC)/ModifiedOpenSeesServices/convergenceTest \
            -I$(RealESSI_SRC)/ModifiedOpenSeesServices/utility \
            -I$(RealESSI_SRC)/ModifiedOpenSeesServices/actor \
            -I$(RealESSI_SRC)/ModifiedOpenSeesServices/actor/channel \
            -I$(RealESSI_SRC)/ModifiedOpenSeesServices/actor/message \
            -I$(RealESSI_SRC)/ModifiedOpenSeesServices/actor/machineBroker \
            -I$(RealESSI_SRC)/ModifiedOpenSeesServices/actor/objectBroker \
            -I$(RealESSI_SRC)/ModifiedOpenSeesServices/actor/actor \
            -I$(RealESSI_SRC)/ModifiedOpenSeesServices/actor/shadow \
            -I$(RealESSI_SRC)/ModifiedOpenSeesServices/actor/address \
            -I$(RealESSI_SRC)/ModifiedOpenSeesServices/tagged/storage \
            -I$(RealESSI_SRC)/ModifiedOpenSeesServices/domain \
            -I$(RealESSI_SRC)/ModifiedOpenSeesServices/domain/domain \
            -I$(RealESSI_SRC)/ModifiedOpenSeesServices/domain/domain/single \
            -I$(RealESSI_SRC)/ModifiedOpenSeesServices/domain/component \
            -I$(RealESSI_SRC)/ModifiedOpenSeesServices/domain/component/storage \
            -I$(RealESSI_SRC)/ModifiedOpenSeesServices/domain/domain/partitioned \
            -I$(RealESSI_SRC)/ModifiedOpenSeesServices/domain/partitioner \
            -I$(RealESSI_SRC)/ModifiedOpenSeesServices/domain/loadBalancer \
            -I$(RealESSI_SRC)/ModifiedOpenSeesServices/domain/subdomain \
            -I$(RealESSI_SRC)/ModifiedOpenSeesServices/domain/region \
            -I$(RealESSI_SRC)/ModifiedOpenSeesServices/domain/node \
            -I$(RealESSI_SRC)/ModifiedOpenSeesServices/domain/load \
            -I$(RealESSI_SRC)/ModifiedOpenSeesServices/domain/damping \
            -I$(RealESSI_SRC)/ModifiedOpenSeesServices/domain/pattern \
            -I$(RealESSI_SRC)/ModifiedOpenSeesServices/domain/groundMotion \
            -I$(RealESSI_SRC)/ModifiedOpenSeesServices/domain/constraints \
            -I$(RealESSI_SRC)/ModifiedOpenSeesServices/domain/region \
            -I$(RealESSI_SRC)/ModifiedOpenSeesServices/element \
            -I$(RealESSI_SRC)/ModifiedOpenSeesServices/analysis    \
            -I$(RealESSI_SRC)/ModifiedOpenSeesServices/analysis/analysis \
            -I$(RealESSI_SRC)/ModifiedOpenSeesServices/analysis/handler \
            -I$(RealESSI_SRC)/ModifiedOpenSeesServices/analysis/numberer \
            -I$(RealESSI_SRC)/ModifiedOpenSeesServices/analysis/algorithm \
            -I$(RealESSI_SRC)/ModifiedOpenSeesServices/analysis/algorithm/eigenAlgo \
            -I$(RealESSI_SRC)/ModifiedOpenSeesServices/analysis/algorithm/equiSolnAlgo \
            -I$(RealESSI_SRC)/ModifiedOpenSeesServices/analysis/algorithm/domainDecompAlgo \
            -I$(RealESSI_SRC)/ModifiedOpenSeesServices/analysis/model \
            -I$(RealESSI_SRC)/ModifiedOpenSeesServices/analysis/model/simple \
            -I$(RealESSI_SRC)/ModifiedOpenSeesServices/analysis/method \
            -I$(RealESSI_SRC)/ModifiedOpenSeesServices/analysis/fe_ele \
            -I$(RealESSI_SRC)/ModifiedOpenSeesServices/analysis/fe_ele/penalty \
            -I$(RealESSI_SRC)/ModifiedOpenSeesServices/analysis/fe_ele/lagrange \
            -I$(RealESSI_SRC)/ModifiedOpenSeesServices/analysis/fe_ele/transformation \
            -I$(RealESSI_SRC)/ModifiedOpenSeesServices/analysis/dof_grp \
            -I$(RealESSI_SRC)/ModifiedOpenSeesServices/analysis/integrator \
            -I$(RealESSI_SRC)/ModifiedOpenSeesServices/system_of_eqn \
            -I$(RealESSI_SRC)/ModifiedOpenSeesServices/system_of_eqn/eigenSOE \
            -I$(RealESSI_SRC)/ModifiedOpenSeesServices/system_of_eqn/linearSOE \
            -I$(RealESSI_SRC)/ModifiedOpenSeesServices/system_of_eqn/linearSOE/slowMatrix \
            -I$(RealESSI_SRC)/ModifiedOpenSeesServices/system_of_eqn/linearSOE/bandSPD \
            -I$(RealESSI_SRC)/ModifiedOpenSeesServices/system_of_eqn/linearSOE/profileSPD \
            -I$(RealESSI_SRC)/ModifiedOpenSeesServices/renderer \
            -I$(RealESSI_SRC)/ModifiedOpenSeesServices/system_of_eqn/linearSOE/fullGEN \
            -I$(RealESSI_SRC)/ModifiedOpenSeesServices/system_of_eqn/linearSOE/bandGEN \
            -I$(RealESSI_SRC)/ModifiedOpenSeesServices/system_of_eqn/linearSOE/sparseGEN \
            -I$(RealESSI_SRC)/ModifiedOpenSeesServices/system_of_eqn/linearSOE/sparseSYM \
            -I$(RealESSI_SRC)/ModifiedOpenSeesServices/system_of_eqn/linearSOE/petsc \
            -I$(RealESSI_SRC)/ModifiedOpenSeesServices/system_of_eqn/linearSOE/umfGEN \
            -I$(RealESSI_SRC)/ModifiedOpenSeesServices/system_of_eqn/linearSOE/cg \
            -I$(RealESSI_SRC)/ModifiedOpenSeesServices/system_of_eqn/linearSOE/BJsolvers \
            -I$(RealESSI_SRC)/ModifiedOpenSeesServices/system_of_eqn/linearSOE/itpack \
            -I$(RealESSI_SRC)/ModifiedOpenSeesServices/system_of_eqn/linearSOE/diagonal \
            -I$(RealESSI_SRC)/ModifiedOpenSeesServices/system_of_eqn/linearSOE/petsc \
            -I$(RealESSI_SRC)/ModifiedOpenSeesServices/system_of_eqn/eigenSOE \
            -I$(RealESSI_SRC)/ModifiedOpenSeesServices/graph/graph \
            -I$(RealESSI_SRC)/ModifiedOpenSeesServices/graph/numberer \
            -I$(RealESSI_SRC)/ModifiedOpenSeesServices/graph/partitioner \
            -I$(RealESSI_SRC)/ModifiedOpenSeesServices/element/nonlinearBeamColumn/element \
            -I$(RealESSI_SRC)/ModifiedOpenSeesServices/element/nonlinearBeamColumn/fiber \
            -I$(RealESSI_SRC)/ModifiedOpenSeesServices/element/nonlinearBeamColumn/matrixutil \
            -I$(RealESSI_SRC)/ModifiedOpenSeesServices/element/nonlinearBeamColumn/quadrule \
            -I$(RealESSI_SRC)/ModifiedOpenSeesServices/coordTransformation \
            -I$(RealESSI_SRC)/ModifiedOpenSeesServices/unittest \
            -I$(RealESSI_SRC)/ModifiedOpenSeesServices \
            -I$(RealESSI_SRC)/ModifiedOpenSeesServices/damage \
            -I$(RealESSI_SRC)/CompGeoMechUCD_MaterialModeling \
            -I$(RealESSI_SRC)/CompGeoMechUCD_MaterialModeling/NewTemplate3Dep \
            -I$(RealESSI_SRC)/CompGeoMechUCD_MaterialModeling/Constitutive_Domain \
            -I$(RealESSI_SRC)/nDarray \
            -I$(RealESSI_SRC)/CompGeoMechUCD_MaterialModeling/Template3Dep \
            -I$(RealESSI_SRC)/CompGeoMechUCD_MaterialModeling/NewTemplate3Dep \
            -I$(RealESSI_SRC)/CompGeoMechUCD_MaterialModeling/Accelerated3Dep \
            -I$(RealESSI_SRC)/CompGeoMechUCD_MaterialModeling/LTensor_Based \
            -I$(RealESSI_SRC)/CompGeoMechUCD_MaterialModeling/FiniteDeformation \
            -I$(RealESSI_SRC)/CompGeoMechUCD_MaterialModeling/FiniteDeformation/fdFlow \
            -I$(RealESSI_SRC)/CompGeoMechUCD_MaterialModeling/FiniteDeformation/fdYield \
            -I$(RealESSI_SRC)/CompGeoMechUCD_MaterialModeling/FiniteDeformation/fdEvolution \
            -I$(RealESSI_SRC)/CompGeoMechUCD_FiniteElements/coupled_u-p_brick_8_nodes \
            -I$(RealESSI_SRC)/CompGeoMechUCD_FiniteElements/coupled_u-p_large_deformation_brick_8_nodes \
            -I$(RealESSI_SRC)/CompGeoMechUCD_FiniteElements/coupled_u-p-U_brick_20_nodes \
            -I$(RealESSI_SRC)/CompGeoMechUCD_FiniteElements/coupled_u-p-U_brick_8_nodes \
            -I$(RealESSI_SRC)/CompGeoMechUCD_FiniteElements/solid_brick_20_nodes \
            -I$(RealESSI_SRC)/CompGeoMechUCD_FiniteElements/solid_brick_20_nodes_elastic \
            -I$(RealESSI_SRC)/CompGeoMechUCD_FiniteElements/solid_brick_27_nodes \
            -I$(RealESSI_SRC)/CompGeoMechUCD_FiniteElements/solid_brick_27_nodes_elastic \
            -I$(RealESSI_SRC)/CompGeoMechUCD_FiniteElements/solid_brick_8_nodes \
            -I$(RealESSI_SRC)/CompGeoMechUCD_FiniteElements/solid_brick_8_nodes_ltensor \
            -I$(RealESSI_SRC)/CompGeoMechUCD_FiniteElements/solid_brick_8_nodes_elastic \
            -I$(RealESSI_SRC)/CompGeoMechUCD_FiniteElements/nonlinear_shear_beam \
            -I$(RealESSI_SRC)/CompGeoMechUCD_FiniteElements/solid_brick_8_nodes_variable_number_of_gauss_points \
            -I$(RealESSI_SRC)/CompGeoMechUCD_FiniteElements/solid_brick_20_nodes_variable_number_of_gauss_points \
            -I$(RealESSI_SRC)/CompGeoMechUCD_FiniteElements/solid_brick_27_nodes_variable_number_of_gauss_points \
            -I$(RealESSI_SRC)/CompGeoMechUCD_FiniteElements/solid_brick_large_deformation_total_Lagrangian_20_nodes \
            -I$(RealESSI_SRC)/CompGeoMechUCD_FiniteElements/solid_brick_large_deformation_total_Lagrangian_8_nodes \
            -I$(RealESSI_SRC)/CompGeoMechUCD_FiniteElements/Contact_Elements \
            -I$(RealESSI_SRC)/CompGeoMechUCD_FiniteElements/elastic_beam \
            -I$(RealESSI_SRC)/CompGeoMechUCD_FiniteElements/rank_one_deficient_elastic_pinned_fixed_beam \
            -I$(RealESSI_SRC)/CompGeoMechUCD_FiniteElements/shell_andes \
            -I$(RealESSI_SRC)/CompGeoMechUCD_FiniteElements/solid_brick_variable_nodes_8_to_27 \
            -I$(RealESSI_SRC)/CompGeoMechUCD_Miscellaneous/units \
            -I$(RealESSI_SRC)/CompGeoMechUCD_Miscellaneous/output \
            -I$(RealESSI_SRC)/CompGeoMechUCD_Miscellaneous/timing \
            -I$(RealESSI_SRC)/UCB_Elements/beamWithHinges \
            -I$(RealESSI_SRC)/UCB_Elements/dispBeamColumn \
            -I$(RealESSI_SRC)/UCB_Elements/elasticBeamLumpedMass \
            -I$(RealESSI_SRC)/UCB_Elements/integration \
            -I$(RealESSI_SRC)/UCB_Elements/shell \
            -I$(RealESSI_SRC)/UCB_Elements/joint \
            -I$(RealESSI_SRC)/UCB_Elements/truss \
            -I$(RealESSI_SRC)/UCB_Elements/zeroLength \
            -I$(RealESSI_SRC)/UCB_Elements/shell \
            -I$(RealESSI_SRC)/API \
            -I$(RealESSI_SRC)/small_utility_programs/ltensor_utilities \
            -I$(RealESSI_SRC)/ltensor


ESSI_LIBS = -L$(RealESSI_SRC)/lib \
      -lcontactelements \
      -lsolid_brick_27_nodes \
      -lsolid_brick_27_nodes_elastic \
      -lsolid_brick_27_nodes_ltensor \
      -lsolid_brick_20_nodes_elastic \
      -lsolid_brick_20_nodes \
      -lsolid_brick_8_nodes \
      -lsolid_brick_8_nodes_ltensor \
      -lsolid_brick_8_nodes_elastic \
      -lsolid_brick_8_nodes_variable_gp \
      -lsolid_brick_20_nodes_variable_gp \
      -lsolid_brick_27_nodes_variable_gp \
      -lnonlinear_shear_beam \
      -lcoupled_u-p-U_brick_8_nodes \
      -lcoupled_u-p_brick_8_nodes \
      -lcoupled_u-p-U_brick_20_nodes \
      -lshell_3_node_andes \
      -lsolid_brick_variable_nodes_8_to_27 \
      -lMOSS \
      -lucbelements \
      -lelasticbeam \
      -lrank_one_deficient_elastic_pinned_fixed_beam \
      -laccelerated3dep \
      -ltemplate3dep \
      -lnewtemplate3dep \
      -lbase_3dep \
      -lltensorbasedmaterials \
      -lclassicelastoplasticmaterials \
      -lndarray \
      -lquantity \
      -lltensorutilities \
      -lessitiming \
      -loutputwriters




            
SEQUENTIAL_NUMERIC_INCLUDES = -I$(RealESSI_Dependencies)/include \
            -I$(RealESSI_Dependencies)/include \
            -I$(RealESSI_Dependencies)/hdf5_sequential/include 


SEQUENTIAL_NUMERIC_LIBS = -L$(RealESSI_Dependencies)/lib/ \
      -llapack \
      -larpack \
      -lumfpack \
      -lamd \
      -lcholmod \
      -lcolamd \
      -lcamd \
      -lccolamd \
      -lmetis \
      -lcblas \
      -lf77blas \
      -latlas \
      -lsuitesparseconfig \
      $(RealESSI_Dependencies)/hdf5_sequential/lib/libhdf5.a 


PARALLEL_NUMERIC_INCLUDES = -I$(RealESSI_Dependencies)/petsc-3.6.0/include \
         -I$(RealESSI_Dependencies)/petsc-3.6.0/arch-linux2-c-opt/include \
         -I$(RealESSI_Dependencies)/parmetis-4.0.2_install/include \
         -I$(RealESSI_Dependencies)/metis-4.0.2_install/include \
         -I$(RealESSI_Dependencies)/hdf5_parallel/include \
         -I$(RealESSI_Dependencies)/include 
         
PARALLEL_NUMERIC_LIBS = -L$(RealESSI_Dependencies)/lib/ \
      -lpetsc \
      -lsuperlu_4.3 \
      -lsuperlu_dist_4.0 \
      -lspai \
      -lscalapack \
      -lflapack \
      -lfblas \
      -lparmetis \
      -lmetis \
      $(RealESSI_Dependencies)/hdf5_parallel/lib/libhdf5.a
      
SEQUENTIAL_MACHINE_LIBS =  \
      -lm \
      -ldl \
      -lz \
      -lgfortran \
      -lieee \
      -lc \
      -lrt

PARALLEL_MACHINE_LIBS = -lm \
      -lgfortran \
      -lquadmath \
      -ldl \
      -lz \
      -lgcc_s \
      -lpthread -lssl -lcrypto

#\
#

