FEIBASEDIR = $(realpath $(dir $(lastword $(MAKEFILE_LIST))))
ESSI_DEPEND_DIR = $(realpath $(dir $(lastword $(MAKEFILE_LIST))))/../essi_dependencies


# ###################################################


ESSI_INCLUDES  = -I$(FEIBASEDIR)/ModifiedOpenSeesServices/matrix \
            -I$(FEIBASEDIR)/ModifiedOpenSeesServices/tagged \
            -I$(FEIBASEDIR)/ModifiedOpenSeesServices/material \
            -I$(FEIBASEDIR)/ModifiedOpenSeesServices/material/uniaxial \
            -I$(FEIBASEDIR)/ModifiedOpenSeesServices/material/uniaxial/fedeas \
            -I$(FEIBASEDIR)/ModifiedOpenSeesServices/material/backbone \
            -I$(FEIBASEDIR)/ModifiedOpenSeesServices/material/state \
            -I$(FEIBASEDIR)/ModifiedOpenSeesServices/material/state/stiffness \
            -I$(FEIBASEDIR)/ModifiedOpenSeesServices/material/state/unloading \
            -I$(FEIBASEDIR)/ModifiedOpenSeesServices/material/state/strength \
            -I$(FEIBASEDIR)/ModifiedOpenSeesServices/material/nD \
            -I$(FEIBASEDIR)/ModifiedOpenSeesServices/material/nD/soil \
            -I$(FEIBASEDIR)/ModifiedOpenSeesServices/material/nD/feap \
            -I$(FEIBASEDIR)/ModifiedOpenSeesServices/material/nD/FiniteDeformation \
            -I$(FEIBASEDIR)/ModifiedOpenSeesServices/material/nD/FiniteDeformation/fdFlow \
            -I$(FEIBASEDIR)/ModifiedOpenSeesServices/material/nD/FiniteDeformation/fdYield \
            -I$(FEIBASEDIR)/ModifiedOpenSeesServices/material/nD/FiniteDeformation/fdEvolution \
            -I$(FEIBASEDIR)/ModifiedOpenSeesServices/material/section \
            -I$(FEIBASEDIR)/ModifiedOpenSeesServices/material/section/repres/cell \
            -I$(FEIBASEDIR)/ModifiedOpenSeesServices/material/section/repres/patch \
            -I$(FEIBASEDIR)/ModifiedOpenSeesServices/material/section/repres/reinfBar \
            -I$(FEIBASEDIR)/ModifiedOpenSeesServices/material/section/repres/reinfLayer \
            -I$(FEIBASEDIR)/ModifiedOpenSeesServices/material/section/repres/section \
            -I$(FEIBASEDIR)/ModifiedOpenSeesServices/material/section/fiber \
            -I$(FEIBASEDIR)/ModifiedOpenSeesServices/material/section/yieldSurface \
            -I$(FEIBASEDIR)/ModifiedOpenSeesServices/material/yieldSurface/evolution \
            -I$(FEIBASEDIR)/ModifiedOpenSeesServices/material/yieldSurface/plasticHardeningMaterial \
            -I$(FEIBASEDIR)/ModifiedOpenSeesServices/material/yieldSurface/yieldSurfaceBC \
            -I$(FEIBASEDIR)/ModifiedOpenSeesServices/recorder \
            -I$(FEIBASEDIR)/ModifiedOpenSeesServices/handler \
            -I$(FEIBASEDIR)/ModifiedOpenSeesServices/database \
            -I$(FEIBASEDIR)/ModifiedOpenSeesServices/convergenceTest \
            -I$(FEIBASEDIR)/ModifiedOpenSeesServices/utility \
            -I$(FEIBASEDIR)/ModifiedOpenSeesServices/actor \
            -I$(FEIBASEDIR)/ModifiedOpenSeesServices/actor/channel \
            -I$(FEIBASEDIR)/ModifiedOpenSeesServices/actor/message \
            -I$(FEIBASEDIR)/ModifiedOpenSeesServices/actor/machineBroker \
            -I$(FEIBASEDIR)/ModifiedOpenSeesServices/actor/objectBroker \
            -I$(FEIBASEDIR)/ModifiedOpenSeesServices/actor/actor \
            -I$(FEIBASEDIR)/ModifiedOpenSeesServices/actor/shadow \
            -I$(FEIBASEDIR)/ModifiedOpenSeesServices/actor/address \
            -I$(FEIBASEDIR)/ModifiedOpenSeesServices/tagged/storage \
            -I$(FEIBASEDIR)/ModifiedOpenSeesServices/domain \
            -I$(FEIBASEDIR)/ModifiedOpenSeesServices/domain/domain \
            -I$(FEIBASEDIR)/ModifiedOpenSeesServices/domain/domain/single \
            -I$(FEIBASEDIR)/ModifiedOpenSeesServices/domain/component \
            -I$(FEIBASEDIR)/ModifiedOpenSeesServices/domain/component/storage \
            -I$(FEIBASEDIR)/ModifiedOpenSeesServices/domain/domain/partitioned \
            -I$(FEIBASEDIR)/ModifiedOpenSeesServices/domain/partitioner \
            -I$(FEIBASEDIR)/ModifiedOpenSeesServices/domain/loadBalancer \
            -I$(FEIBASEDIR)/ModifiedOpenSeesServices/domain/subdomain \
            -I$(FEIBASEDIR)/ModifiedOpenSeesServices/domain/region \
            -I$(FEIBASEDIR)/ModifiedOpenSeesServices/domain/node \
            -I$(FEIBASEDIR)/ModifiedOpenSeesServices/domain/load \
            -I$(FEIBASEDIR)/ModifiedOpenSeesServices/domain/damping \
            -I$(FEIBASEDIR)/ModifiedOpenSeesServices/domain/pattern \
            -I$(FEIBASEDIR)/ModifiedOpenSeesServices/domain/groundMotion \
            -I$(FEIBASEDIR)/ModifiedOpenSeesServices/domain/constraints \
            -I$(FEIBASEDIR)/ModifiedOpenSeesServices/domain/region \
            -I$(FEIBASEDIR)/ModifiedOpenSeesServices/element \
            -I$(FEIBASEDIR)/ModifiedOpenSeesServices/analysis    \
            -I$(FEIBASEDIR)/ModifiedOpenSeesServices/analysis/analysis \
            -I$(FEIBASEDIR)/ModifiedOpenSeesServices/analysis/handler \
            -I$(FEIBASEDIR)/ModifiedOpenSeesServices/analysis/numberer \
            -I$(FEIBASEDIR)/ModifiedOpenSeesServices/analysis/algorithm \
            -I$(FEIBASEDIR)/ModifiedOpenSeesServices/analysis/algorithm/eigenAlgo \
            -I$(FEIBASEDIR)/ModifiedOpenSeesServices/analysis/algorithm/equiSolnAlgo \
            -I$(FEIBASEDIR)/ModifiedOpenSeesServices/analysis/algorithm/domainDecompAlgo \
            -I$(FEIBASEDIR)/ModifiedOpenSeesServices/analysis/model \
            -I$(FEIBASEDIR)/ModifiedOpenSeesServices/analysis/model/simple \
            -I$(FEIBASEDIR)/ModifiedOpenSeesServices/analysis/method \
            -I$(FEIBASEDIR)/ModifiedOpenSeesServices/analysis/fe_ele \
            -I$(FEIBASEDIR)/ModifiedOpenSeesServices/analysis/fe_ele/penalty \
            -I$(FEIBASEDIR)/ModifiedOpenSeesServices/analysis/fe_ele/lagrange \
            -I$(FEIBASEDIR)/ModifiedOpenSeesServices/analysis/fe_ele/transformation \
            -I$(FEIBASEDIR)/ModifiedOpenSeesServices/analysis/dof_grp \
            -I$(FEIBASEDIR)/ModifiedOpenSeesServices/analysis/integrator \
            -I$(FEIBASEDIR)/ModifiedOpenSeesServices/system_of_eqn \
            -I$(FEIBASEDIR)/ModifiedOpenSeesServices/system_of_eqn/eigenSOE \
            -I$(FEIBASEDIR)/ModifiedOpenSeesServices/system_of_eqn/linearSOE \
            -I$(FEIBASEDIR)/ModifiedOpenSeesServices/system_of_eqn/linearSOE/slowMatrix \
            -I$(FEIBASEDIR)/ModifiedOpenSeesServices/system_of_eqn/linearSOE/bandSPD \
            -I$(FEIBASEDIR)/ModifiedOpenSeesServices/system_of_eqn/linearSOE/profileSPD \
            -I$(FEIBASEDIR)/ModifiedOpenSeesServices/renderer \
            -I$(FEIBASEDIR)/ModifiedOpenSeesServices/system_of_eqn/linearSOE/fullGEN \
            -I$(FEIBASEDIR)/ModifiedOpenSeesServices/system_of_eqn/linearSOE/bandGEN \
            -I$(FEIBASEDIR)/ModifiedOpenSeesServices/system_of_eqn/linearSOE/sparseGEN \
            -I$(FEIBASEDIR)/ModifiedOpenSeesServices/system_of_eqn/linearSOE/sparseSYM \
            -I$(FEIBASEDIR)/ModifiedOpenSeesServices/system_of_eqn/linearSOE/petsc \
            -I$(FEIBASEDIR)/ModifiedOpenSeesServices/system_of_eqn/linearSOE/umfGEN \
            -I$(FEIBASEDIR)/ModifiedOpenSeesServices/system_of_eqn/linearSOE/cg \
            -I$(FEIBASEDIR)/ModifiedOpenSeesServices/system_of_eqn/linearSOE/BJsolvers \
            -I$(FEIBASEDIR)/ModifiedOpenSeesServices/system_of_eqn/linearSOE/itpack \
            -I$(FEIBASEDIR)/ModifiedOpenSeesServices/system_of_eqn/linearSOE/diagonal \
            -I$(FEIBASEDIR)/ModifiedOpenSeesServices/system_of_eqn/linearSOE/petsc \
            -I$(FEIBASEDIR)/ModifiedOpenSeesServices/system_of_eqn/eigenSOE \
            -I$(FEIBASEDIR)/ModifiedOpenSeesServices/graph/graph \
            -I$(FEIBASEDIR)/ModifiedOpenSeesServices/graph/numberer \
            -I$(FEIBASEDIR)/ModifiedOpenSeesServices/graph/partitioner \
            -I$(FEIBASEDIR)/ModifiedOpenSeesServices/element/nonlinearBeamColumn/element \
            -I$(FEIBASEDIR)/ModifiedOpenSeesServices/element/nonlinearBeamColumn/fiber \
            -I$(FEIBASEDIR)/ModifiedOpenSeesServices/element/nonlinearBeamColumn/matrixutil \
            -I$(FEIBASEDIR)/ModifiedOpenSeesServices/element/nonlinearBeamColumn/quadrule \
            -I$(FEIBASEDIR)/ModifiedOpenSeesServices/coordTransformation \
            -I$(FEIBASEDIR)/ModifiedOpenSeesServices/unittest \
            -I$(FEIBASEDIR)/ModifiedOpenSeesServices \
            -I$(FEIBASEDIR)/ModifiedOpenSeesServices/damage \
            -I$(FEIBASEDIR)/CompGeoMechUCD_MaterialModeling \
            -I$(FEIBASEDIR)/CompGeoMechUCD_MaterialModeling/NewTemplate3Dep \
            -I$(FEIBASEDIR)/CompGeoMechUCD_MaterialModeling/Constitutive_Domain \
            -I$(FEIBASEDIR)/nDarray \
            -I$(FEIBASEDIR)/CompGeoMechUCD_MaterialModeling/Template3Dep \
            -I$(FEIBASEDIR)/CompGeoMechUCD_MaterialModeling/NewTemplate3Dep \
            -I$(FEIBASEDIR)/CompGeoMechUCD_MaterialModeling/Accelerated3Dep \
            -I$(FEIBASEDIR)/CompGeoMechUCD_MaterialModeling/LTensor_Based \
            -I$(FEIBASEDIR)/CompGeoMechUCD_MaterialModeling/FiniteDeformation \
            -I$(FEIBASEDIR)/CompGeoMechUCD_MaterialModeling/FiniteDeformation/fdFlow \
            -I$(FEIBASEDIR)/CompGeoMechUCD_MaterialModeling/FiniteDeformation/fdYield \
            -I$(FEIBASEDIR)/CompGeoMechUCD_MaterialModeling/FiniteDeformation/fdEvolution \
            -I$(FEIBASEDIR)/CompGeoMechUCD_FiniteElements/coupled_u-p_brick_8_nodes \
            -I$(FEIBASEDIR)/CompGeoMechUCD_FiniteElements/coupled_u-p_large_deformation_brick_8_nodes \
            -I$(FEIBASEDIR)/CompGeoMechUCD_FiniteElements/coupled_u-p-U_brick_20_nodes \
            -I$(FEIBASEDIR)/CompGeoMechUCD_FiniteElements/coupled_u-p-U_brick_8_nodes \
            -I$(FEIBASEDIR)/CompGeoMechUCD_FiniteElements/solid_brick_20_nodes \
            -I$(FEIBASEDIR)/CompGeoMechUCD_FiniteElements/solid_brick_20_nodes_elastic \
            -I$(FEIBASEDIR)/CompGeoMechUCD_FiniteElements/solid_brick_27_nodes \
            -I$(FEIBASEDIR)/CompGeoMechUCD_FiniteElements/solid_brick_27_nodes_elastic \
            -I$(FEIBASEDIR)/CompGeoMechUCD_FiniteElements/solid_brick_8_nodes \
            -I$(FEIBASEDIR)/CompGeoMechUCD_FiniteElements/solid_brick_8_nodes_ltensor \
            -I$(FEIBASEDIR)/CompGeoMechUCD_FiniteElements/solid_brick_8_nodes_elastic \
            -I$(FEIBASEDIR)/CompGeoMechUCD_FiniteElements/nonlinear_shear_beam \
            -I$(FEIBASEDIR)/CompGeoMechUCD_FiniteElements/solid_brick_8_nodes_variable_number_of_gauss_points \
            -I$(FEIBASEDIR)/CompGeoMechUCD_FiniteElements/solid_brick_20_nodes_variable_number_of_gauss_points \
            -I$(FEIBASEDIR)/CompGeoMechUCD_FiniteElements/solid_brick_27_nodes_variable_number_of_gauss_points \
            -I$(FEIBASEDIR)/CompGeoMechUCD_FiniteElements/solid_brick_large_deformation_total_Lagrangian_20_nodes \
            -I$(FEIBASEDIR)/CompGeoMechUCD_FiniteElements/solid_brick_large_deformation_total_Lagrangian_8_nodes \
            -I$(FEIBASEDIR)/CompGeoMechUCD_FiniteElements/Contact_Elements \
            -I$(FEIBASEDIR)/CompGeoMechUCD_FiniteElements/penalty_element \
            -I$(FEIBASEDIR)/CompGeoMechUCD_FiniteElements/penalty_element_apply_displacement \
            -I$(FEIBASEDIR)/CompGeoMechUCD_FiniteElements/elastic_beam \
            -I$(FEIBASEDIR)/CompGeoMechUCD_FiniteElements/rank_one_deficient_elastic_pinned_fixed_beam \
            -I$(FEIBASEDIR)/CompGeoMechUCD_FiniteElements/shell_andes \
            -I$(FEIBASEDIR)/CompGeoMechUCD_FiniteElements/solid_brick_variable_nodes_8_to_27 \
            -I$(FEIBASEDIR)/CompGeoMechUCD_Miscellaneous/units \
            -I$(FEIBASEDIR)/CompGeoMechUCD_Miscellaneous/output \
            -I$(FEIBASEDIR)/CompGeoMechUCD_Miscellaneous/timing \
            -I$(FEIBASEDIR)/UCB_Elements/beamWithHinges \
            -I$(FEIBASEDIR)/UCB_Elements/dispBeamColumn \
            -I$(FEIBASEDIR)/UCB_Elements/elasticBeamLumpedMass \
            -I$(FEIBASEDIR)/UCB_Elements/integration \
            -I$(FEIBASEDIR)/UCB_Elements/shell \
            -I$(FEIBASEDIR)/UCB_Elements/joint \
            -I$(FEIBASEDIR)/UCB_Elements/truss \
            -I$(FEIBASEDIR)/UCB_Elements/zeroLength \
            -I$(FEIBASEDIR)/UCB_Elements/shell \
            -I$(FEIBASEDIR)/API \
            -I$(FEIBASEDIR)/small_utility_programs/ltensor_utilities

#            -I$(FEIBASEDIR)/ModifiedOpenSeesServices/response \

ESSI_LIBS = -L$(FEIBASEDIR)/lib \
      -lcontactelements \
      -lsolid_brick_27_nodes \
      -lsolid_brick_27_nodes_elastic \
      -lsolid_brick_27_nodes_ltensor \
      -lsolid_brick_20_nodes_elastic \
      -lsolid_brick_20_nodes \
      -lsolid_brick_8_nodes \
      -lsolid_brick_8_nodes_ltensor \
      -lsolid_brick_8_nodes_elastic \
      -lsolid_brick_8_nodes_variable_gp \
      -lsolid_brick_20_nodes_variable_gp \
      -lsolid_brick_27_nodes_variable_gp \
      -lnonlinear_shear_beam \
      -lcoupled_u-p-U_brick_8_nodes \
      -lcoupled_u-p_brick_8_nodes \
      -lcoupled_u-p-U_brick_20_nodes \
      -lshell_3_node_andes \
      -lsolid_brick_variable_nodes_8_to_27 \
      -lMOSS \
      -lucbelements \
      -lelasticbeam \
      -lrank_one_deficient_elastic_pinned_fixed_beam \
      -laccelerated3dep \
      -ltemplate3dep \
      -lnewtemplate3dep \
      -lpenaltyelement \
      -lpenaltyelementapplydisplacement \
      -lbase_3dep \
      -lltensorbasedmaterials \
      -lndarray \
      -lquantity \
      -lltensorutilities \
      -lessitiming \
      -loutputwriters




            
SEQUENTIAL_NUMERIC_INCLUDES = -I$(ESSI_DEPEND_DIR)/lib/include \
            -I$(ESSI_DEPEND_DIR)/include \
            -I$(ESSI_DEPEND_DIR)/ATLAS/include \
            -I$(ESSI_DEPEND_DIR)/hdf5_sequential/include 


SEQUENTIAL_NUMERIC_LIBS = -L$(ESSI_DEPEND_DIR)/lib/ \
      -llapack \
      -larpack \
      -lumfpack \
      -lamd \
      -lcholmod \
      -lcolamd \
      -lcamd \
      -lccolamd \
      -lmetis \
      -lcblas \
      -lf77blas \
      -latlas \
      -lsuitesparseconfig \
      $(ESSI_DEPEND_DIR)/hdf5_sequential/lib/libhdf5.a 


PARALLEL_NUMERIC_INCLUDES = -I$(ESSI_DEPEND_DIR)/petsc-3.6.0/include \
         -I$(ESSI_DEPEND_DIR)/petsc-3.6.0/arch-linux2-c-opt/include \
         -I$(ESSI_DEPEND_DIR)/parmetis-4.0.2_install/include \
         -I$(ESSI_DEPEND_DIR)/metis-4.0.2_install/include \
         -I$(ESSI_DEPEND_DIR)/hdf5_parallel/include
         
# -I/usr/lib/openmpi/include \
# -I/usr/lib/openmpi/include/openmpi \

PARALLEL_NUMERIC_LIBS = $(ESSI_DEPEND_DIR)/petsc-3.6.0/arch-linux2-c-opt/lib/libpetsc.a \
      $(ESSI_DEPEND_DIR)/petsc-3.6.0/arch-linux2-c-opt/lib/libsuperlu_4.3.a \
      $(ESSI_DEPEND_DIR)/petsc-3.6.0/arch-linux2-c-opt/lib/libsuperlu_dist_4.0.a \
      $(ESSI_DEPEND_DIR)/petsc-3.6.0/arch-linux2-c-opt/lib/libspai.a \
      $(ESSI_DEPEND_DIR)/petsc-3.6.0/arch-linux2-c-opt/lib/libscalapack.a \
      $(ESSI_DEPEND_DIR)/petsc-3.6.0/arch-linux2-c-opt/lib/libflapack.a \
      $(ESSI_DEPEND_DIR)/petsc-3.6.0/arch-linux2-c-opt/lib/libfblas.a \
      $(ESSI_DEPEND_DIR)/parmetis-4.0.2_install/lib/libparmetis.a \
      $(ESSI_DEPEND_DIR)/metis-4.0.2_install/lib/libmetis.a \
      $(ESSI_DEPEND_DIR)/hdf5_parallel/lib/libhdf5.a 
      
# $(ESSI_DEPEND_DIR)/petsc-3.6.0/externalpackages/spooles-2.2-dec-2008/libspooles.a \
# $(ESSI_DEPEND_DIR)/petsc-3.6.0/arch-linux2-c-opt/lib/libPLAPACK.a \
# $(ESSI_DEPEND_DIR)/petsc-3.6.0/arch-linux2-c-opt/lib/libblacs.a \
# $(ESSI_DEPEND_DIR)/petsc-3.6.0/arch-linux2-c-opt/lib/libspooles.a \
# $(ESSI_DEPEND_DIR)/petsc-3.6.0/arch-linux2-c-opt/lib/libHYPRE.a \


SEQUENTIAL_MACHINE_LIBS =  \
      -lm \
      -ldl \
      -lz \
      -lgfortran \
      -lieee \
      -lc 
#      -lboost

PARALLEL_MACHINE_LIBS = -lm \
      -lgfortran \
      -lquadmath \
      -ldl \
      -lz \
      -lgcc_s \
      -lpthread \
      -lssl -lcrypto

# -L$(FEIBASEDIR)/lib \
